apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # Робить сервіс доступним на IP-адресі вузла та статичному порту (NodePort)
  type: ClusterIP
  # Для хмарних провайдерів можна використовувати LoadBalancer
  # type: LoadBalancer
