apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: Y2xvdWRfZGI= # cloud_db
  POSTGRES_USER: Y2xvdWRfdXNlcg== # cloud_user
  POSTGRES_PASSWORD: c3Ryb25ncGFzc3dvcmQxMjM= # strongpassword123
